### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by datnamer** [jrevels/Cassette.jl#105]
Can cassette intercept and rewrite loops? Like for example rearrange loops for different hardware  and array types (threaded, GPU, distributed topology etc)

**Comment by oxinabox** [comment]
YEs, but it ineed to be done with a IR `@pass`.
Which are honestly faily  hard core, not fit for human consumption, make my face hurt kinda things.
(or maybe I am jsut a whimp)

**Comment by datnamer** [comment]
Maybe it's better to do at the AST level? I don't know much about metaprogramming.

**Comment by vchuravy** [comment]
Cassette does give you access to "a" level of representation in which you can try to recognize for-loops, but as @oxinabox is not the most friendly form for folks who are new to compiler development.
You have much easier access to for-loops on the macro level, but in both Cassette and the macro you don't have access to type-information.

So it depends on what kind of thing you want to do, but I suspect Cassette is not quite the right tool. It can certainly help with parts of it, and it would be cool if we had a "loop information pass" that you can run on the CodeInfo object and recover information about the loop structure.

**Comment by datnamer** [comment]
@vchuravy  I think GPUifyloops does essentially what i was looking for.
