### ISSUE TITLE
`@pure` seems to cause issues!

### ISSUE THREAD

**Issue by vchuravy** [jrevels/Cassette.jl#108]
```
Base.@pure datatype_align(::Type{T}) where T = T.layout

function broken(::Type{T}) where {T}
     align = datatype_align(T)
     Val(align)
end

using Cassette
Cassette.@context CUDACtx
const cudactx = Cassette.disablehooks(CUDACtx())

# Comment this out 
function Cassette.overdub(::CUDACtx, ::typeof(datatype_align), ::Type{T}) where T
    datatype_align(T)
end
```

**Comment by jrevels** [comment]
This is actually a great find. The problem, I guess, is that we're taking a call to an `@pure` function and we're replacing that with a call to an `overdub` of that function, which is not marked `@pure` and is a generated function. 

My guess is that we can solve this by "propagating" `@pure`ness to the overdubbed call, e.g. if the compiler considers `f(args...)` to be an `@pure` call then we'd want it to consider `overdub(ctx, f, args...)` to be an `@pure` call.

I wonder how many outstanding perf issues that would solve.

**Comment by jrevels** [comment]
Hmm. `pure` is a `CodeInfo` field that Cassette already propagates correctly. However, the `pure` field is set to `false` for the corresponding `overdub` method:

```julia
julia> using Cassette

julia> Cassette.@context Ctx;

julia> Base.@pure f() = 1
f (generic function with 1 method)

julia> (@code_lowered Cassette.overdub(Ctx(), f)).pure
true

julia> first(methods(Cassette.overdub, (typeof(Ctx()), typeof(f))).ms).pure
false
```

Is it possible that the compiler is checking the corresponding method field when it "should" be checking the CodeInfo field ("should" from Cassette's POV, not in an absolute sense)?

**Comment by jrevels** [comment]
ref https://github.com/JuliaLang/julia/blob/abb09f88804c4e74c752a66157e767c9b0f8945d/base/compiler/abstractinterpretation.jl#L558

**Comment by jrevels** [comment]
ref https://github.com/JuliaLang/julia/pull/31012

**Comment by oxinabox** [comment]
Given the user is likely not aware that they are overdubbing a pure function...
this feels like a dangerious thing.

**Comment by vchuravy** [comment]
This primarily impacts users of the pass functionality, where you can query and set `pure` on the codeinfo object. If you are adding non-pure effects you will want to do this. It shouldn't impact overdub method definitions. The change upstream makes sure that we will abide the CI.pure flag. Caveat emptor.
