### ISSUE TITLE
Method definition overdub(...) overwritten in module ...

### ISSUE THREAD

**Issue by dfdx** [jrevels/Cassette.jl#145]
While loading my library Yota which uses Cassette for execution tracing I get the following warnings (and similar for `recurse` method):
```
WARNING: Method definition overdub(Cassette.Context{N, M, T, P, B, H} where H<:Union{Cassette.DisableHooks, Nothing} where B<:Union{Nothing, Base.IdDict{Module, Base.Dict{Symbol, Cassette.BindingMeta}}} where P<:Cassette.AbstractPass where T<:Union{Nothing, Cassette.Tag{N, X, E} where E where X where N<:Cassette.AbstractContextName} where M where N<:Cassette.AbstractContextName, Any...)
 in module Cassette at /home/user/.julia/packages/Cassette/YCOeN/src/overdub.jl:524 
 overwritten in module Yota at /home/user/.julia/packages/Cassette/YCOeN/src/overdub.jl:524.
  ** incremental compilation may be fatally broken for this module **
```
Things to note: 

1. I only define [`Cassette.overdub()`](https://github.com/dfdx/Yota.jl/blob/master/src/trace/cassette.jl#L93), but not `Overdub.recurse` (although I [call it](https://github.com/dfdx/Yota.jl/blob/master/src/trace/cassette.jl#L108)).
2. Though warning message says "overwritten in module Yota", the following path actually points to Cassette. 

These warnings don't break any code, but they appear in every session, sometimes even twice if I import Yota from another module. Am I doing something dumb here?

**Comment by oxinabox** [comment]
This is #113

**Comment by dfdx** [comment]
Got it, thanks!
