### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by MasonProtter** [jrevels/Cassette.jl#171]
Looks like there's at least once issue in ForwardDiff2 that would be fixed by tagging a patch release of Cassette: https://github.com/YingboMa/ForwardDiff2.jl/issues/43

It would be nice if a new version could be tagged.

**Comment by ffevotte** [comment]
There are also 2 issues in [`GFlops`](https://github.com/triscale-innov/GFlops.jl) that would be fixed by a new release of Cassette:
- triscale-innov/GFlops.jl#6
- triscale-innov/GFlops.jl#10

Thanks in advance!

**Comment by vchuravy** [comment]
I have been looking at it, but the `apply_iterate` handling regresses inference and allocations on 1.4

**Comment by ffevotte** [comment]
You mean that the current master of Cassette is worse (in terms of inference and allocations for Julia v1.4) than Cassette v0.3.1 (in which some of the `apply_iterate` handling had already been integrated)?

**Comment by vchuravy** [comment]
Should be fixed by #172

**Comment by ffevotte** [comment]
Thanks!
