### ISSUE TITLE
invalid pcre ccall error message 

### ISSUE THREAD

**Issue by jrevels** [jrevels/Cassette.jl#61]
Might be from the depwarn? Just overdubbing the depwarn doesn't trigger it though...

```
julia> using Cassette

julia> Cassette.@context Ctx

julia> Cassette.recurse(Ctx(), Vector{Any}, 1)
Exception handling log message: TypeError(:recurse, "ccall: first argument not a pointer or valid constant expression", Ptr, (:pcre2_match_8, "libpcre2-8"))
  module=Cassette  file=/Users/jarrettrevels/.julia/dev/Cassette/src/overdub.jl  line=0
  Second exception: TypeError(:recurse, "ccall: first argument not a pointer or valid constant expression", Ptr, (:pcre2_match_8, "libpcre2-8"))
1-element Array{Any,1}:
 #undef
```

**Comment by vchuravy** [comment]
I think `ccall` has specific linearization requirements for the IR and it is checking if the arguments are constant, maybe we added a level of indirection here that messes that up?

**Comment by jrevels** [comment]
We did emit calls that messed that up before (https://github.com/jrevels/Cassette.jl/pull/52), but I thought I had fixed it...
