### ISSUE TITLE
Overdubs that depend on overdubs don't work?

### ISSUE THREAD

**Issue by oxinabox** [jrevels/Cassette.jl#87]
```
using Cassette
foobar(args...) = 0 
Cassette.@context CTX3
Cassette.execute(::CTX3, ::typeof(foobar), b) = foobar(identity, b)
Cassette.execute(::CTX3, ::typeof(foobar), a::Function, b) = b

Cassette.overdub(CTX3(), foobar, 1) 
# Expected result 1,
#  actual result 0.
```

This is a respoduction of https://github.com/invenia/Mocking.jl/issues/59
Which I kinda thought switching to Cassette woiuld fix.

**Comment by jrevels** [comment]
I think there's a misunderstanding - `0` is exactly the expected output for the code you wrote. Your code basically says "when overdubbing, replace `foobar(b)` with a call to `foobar(identity, b)`". `foobar(identity, b)`, of course, dispatches to the only available `foobar` method, which just returns `0`.

Did you mean to define

```julia
Cassette.execute(ctx::CTX3, ::typeof(foobar), b) = Cassette.@overdub(ctx, foobar(identity, b))
```

and invoke your test call like

```julia
Cassette.@overdub(CTX3(), foobar(1))
```

? That should (and does, I just checked) yield the result `1`.

The documentation [here](https://jrevels.github.io/Cassette.jl/latest/contextualdispatch.html) might help, especially this paragraph (of course, it only makes sense when read in context, so definitely do that): 

> Actually, there's a subtlety about overdub here we should address before moving on. Why wasn't the first line in the trace log `/(1, 2)`? I'll leave the answer as an exercise to the reader - just recall the definition of overdub from the previous section. If this the barrier between the overdub and the contextual dispatch interface seems confusing, try comparing the output from the above example with the output generated via `overdub(Ctx(), () -> 1/2)`.

**Comment by oxinabox** [comment]
Thanks @jrevels,
I'll read the docs linked in a second.

Just to record my thoughts first (perhaps useful to future people who run into this, or maybe for thinking about the docs.)

> Your code basically says "when overdubbing, replace foobar(b) with a call to foobar(identity, b)". foobar(identity, b), of course, dispatches to the only available foobar method, which just returns 0.

I thought my code said: _when overdubbing_:
 - _ "replace `foobar(b)` with a call to `foobar(identity, b)`"
 -  and _"replace `foobar(a::Function, b)` with `b`

more notes will follow.
I think this is going to boil down to overdub being like MacroTools' `postwalk` rather than `prewalk`
